# Generated by Django 4.2.8 on 2024-01-19 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import utils.custom_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tokens",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "ticker_symbol",
                    models.CharField(db_index=True, max_length=15, unique=True, verbose_name="Token Symbol"),
                ),
                ("ticker_slug", models.SlugField(max_length=255, verbose_name="Token Slug")),
                ("ticker_id", models.IntegerField(verbose_name="Token ID")),
                ("ticker_name", models.CharField(max_length=255, verbose_name="Token Name")),
                ("total_supply", models.FloatField(default=0.0)),
                ("circulating_supply", models.FloatField(default=0.0)),
                ("usd_price", models.FloatField(default=0.0)),
                ("chf_price", models.FloatField(default=0.0)),
                ("chy_price", models.FloatField(default=0.0)),
                ("eur_price", models.FloatField(default=0.0)),
                ("ngn_price", models.FloatField(default=0.0)),
                ("gbp_price", models.FloatField(default=0.0)),
                ("zar_price", models.FloatField(default=0.0)),
                ("sar_price", models.FloatField(default=0.0)),
                ("sek_price", models.FloatField(default=0.0)),
                ("aed_price", models.FloatField(default=0.0)),
                ("token_address", models.CharField(blank=True, max_length=15, verbose_name="Token Contract Address")),
                ("token_abi", models.TextField(blank=True, verbose_name="Token Contract ABI")),
                (
                    "token_router_address",
                    models.CharField(blank=True, max_length=15, verbose_name="Token Router Address"),
                ),
                ("token_router_abi", models.TextField(blank=True, verbose_name="Token Router ABI")),
                ("listed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WatchAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("users", utils.custom_fields.ListField()),
                ("address", models.CharField(max_length=500, unique=True)),
                ("top_earning", models.FloatField(default=0.0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WatchToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("groups", utils.custom_fields.ListField()),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="watched_token", to="tokens.tokens"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
