# Generated by Django 4.2.8 on 2024-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="must_have_about",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="must_have_description",
            field=models.BooleanField(default=True),
        ),
    ]
