# Generated by Django 4.2.8 on 2024-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_groupoffenders_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupoffenders",
            name="warned_times",
            field=models.IntegerField(default=3),
        ),
    ]
