# Generated by Django 4.2.8 on 2024-01-20 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_groupoffenders_warned_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramGroupMediaActions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("images", models.IntegerField(default=0)),
                ("videos", models.IntegerField(default=0)),
                ("animation", models.IntegerField(default=0)),
                ("audio", models.IntegerField(default=0)),
                ("sticker", models.IntegerField(default=0)),
                ("documents", models.IntegerField(default=0)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_actions",
                        to="users.telegramgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
