# Generated by Django 4.2.8 on 2024-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_telegramgroupmediaactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="allow_hash",
            field=models.BooleanField(default=False),
        ),
    ]
