# Generated by Django 4.2.8 on 2024-01-20 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_telegramgroup_allow_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="enable_captcha",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="expire_verification",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TelegramGroupFlooding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("messages_before_block", models.IntegerField(default=5)),
                ("repeats_timeframe", models.IntegerField(default=3)),
                ("ban", models.BooleanField(default=True)),
                ("kick", models.BooleanField(default=False)),
                ("mute", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flood_settings",
                        to="users.telegramgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
