# Generated by Django 4.2.8 on 2024-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_telegramgroup_enable_captcha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="unverified_user_duration",
            field=models.IntegerField(default=7),
        ),
    ]
