# Generated by Django 4.2.8 on 2024-01-21 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_telegramgroup_unverified_user_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="expire_verification",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verified",
        ),
        migrations.CreateModel(
            name="TelegramGroupCaptcha",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("captcha_code", models.IntegerField(unique=True)),
                ("expires", models.DateTimeField(null=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="captcha", to="users.telegramgroup"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
