# Generated by Django 4.2.8 on 2024-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_expire_verification_remove_user_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
