# Generated by Django 4.2.8 on 2024-01-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(unique=True)),
                ("total_subscriptions", models.IntegerField(default=0)),
                ("daily_logged_in_users", models.IntegerField(default=0)),
                ("new_registrations", models.IntegerField(default=0)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
