# Generated by Django 4.2.8 on 2024-02-08 14:06

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                ("group_id", models.IntegerField(null=True, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("payment_successful", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "ordering": ["-created"],
            },
        ),
    ]
